export const driverNames = [
  "Max Verstappen",
  "Charles Leclerc",
  "Sergio Perez",
  "George Russell",
  "Carlos Sainz",
  "Lewis Hamilton",
  "Lando Norris",
  "Esteban Ocon",
  "Fernando Alonso",
  "Valtteri Bottas",
  "Daniel Ricciardo",
  "Sebastian Vettel",
  "Kevin Magnussen",
  "Pierre Gasly",
  "Lance Stroll",
  "Mick Schumacher",
  "Yuki Tsunoda",
  "Zhou Guanyu",
  "Alexander Albon",
  "Nicholas Latifi",
  "Nyck De Vries",
  "Nico Hulkenberg",
  "Logan Sargeant",
  "Oscar Piastri",
]